#pragma once
// icon_assets_baked.h — Lookup for icons baked into firmware flash.
//
// The bodies in icon_assets_baked.cpp are generated by
// scripts/bake_icons_to_c.py from the .bin files under data/assets. Only the
// dashboard-critical icons (theme day/night, button icons used by the bundled
// dashboard) are baked — keeps app-flash footprint at ~8 KB while resolving
// the SPIFFS cache miss path that left buttons blank after page navigation
// (issue #1261).
//
// Icons NOT in the baked set keep the existing SPIFFS-loaded path via
// IconAssets::path() and remain available for user-customized dashboards.

#include <lvgl.h>

namespace IconAssetsBaked {

// Returns a pointer to the baked dsc when `iconName` matches one of the
// bundled icons; `nullptr` otherwise. Safe with empty / null input.
const lv_img_dsc_t *resolve(const char *iconName);

} // namespace IconAssetsBaked
