// Generated by scripts/gen_monogram_c.py — do not edit.
#pragma once

#include <lvgl.h>

namespace MonogramBaked {
const lv_img_dsc_t *mark();
const lv_img_dsc_t *header();
} // namespace MonogramBaked
