#!/usr/bin/env python3
# bake_icons_to_c.py — Bake selected LVGL .bin icons into a C++ source file.
#
# Reads the listed .bin files under data/assets and emits a single
# `src/ui/icon_assets_baked.cpp` that exposes one `const lv_img_dsc_t` per
# icon plus a name -> dsc lookup helper. Baked icons are read-only flash
# pointers — no SPIFFS access, no decoder allocation, no image-cache life
# math, no heap gate. Resolves the page-rebuild "icon vanished" bug for
# the dashboard buttons (issue #1261).
#
# Source format (LVGL 8.x):
#   bytes 0..3 : packed lv_img_header_t (cf:5 | w:11 | h:11 | reserved:5)
#   bytes 4..  : pixel payload
#
# We only generate `cf = LV_IMG_CF_TRUE_COLOR_ALPHA` (5) — every shipped
# icon was rendered with the alpha pipeline (build_sensor_icons.py).

from __future__ import annotations

import shutil
import struct
import subprocess
import sys
from pathlib import Path

LV_IMG_CF_TRUE_COLOR_ALPHA = 5

# (lookup key passed by consumers, source .bin path under data/assets)
#   - Theme icons use the `icon_day` / `icon_night` names directly from top_bar.cpp.
#   - Button icons use the `SensorIconName` key from canshift-core
#     (`map_icon`, `launch`, `flame`, ...). The C symbol stem mirrors the
#     lookup key so the registry entry stays grep-friendly.
BAKED_ICONS = [
    ("icon_day", "icon_day.bin"),
    ("icon_night", "icon_night.bin"),
    ("map_icon", "sensor_map_icon.bin"),
    ("launch", "sensor_launch.bin"),
    ("flame", "sensor_flame.bin"),
]

ROOT = Path(__file__).resolve().parent.parent
ASSETS_DIR = ROOT / "data" / "assets"
OUT_FILE = ROOT / "src" / "ui" / "icon_assets_baked.cpp"


def parse_header(blob: bytes) -> tuple[int, int, int]:
    if len(blob) < 4:
        raise ValueError("file too small for an LVGL header")
    packed = struct.unpack("<I", blob[:4])[0]
    cf = packed & 0x1F
    w = (packed >> 10) & 0x7FF
    h = (packed >> 21) & 0x7FF
    return cf, w, h


def hex_dump(data: bytes, indent: str = "    ") -> str:
    lines: list[str] = []
    chunk = 16
    for i in range(0, len(data), chunk):
        row = ", ".join(f"0x{b:02X}" for b in data[i : i + chunk])
        lines.append(f"{indent}{row},")
    return "\n".join(lines)


def main() -> int:
    entries: list[str] = []
    name_map: list[str] = []

    for stem, fname in BAKED_ICONS:
        src = ASSETS_DIR / fname
        if not src.is_file():
            raise SystemExit(f"ERROR: missing source {src}")
        blob = src.read_bytes()
        cf, w, h = parse_header(blob)
        if cf != LV_IMG_CF_TRUE_COLOR_ALPHA:
            raise SystemExit(f"ERROR: {fname} cf={cf}, only TRUE_COLOR_ALPHA (5) baker is supported")
        payload = blob[4:]
        expected = w * h * 3
        if len(payload) != expected:
            raise SystemExit(
                f"ERROR: {fname} payload size {len(payload)} != w*h*3 = {expected}"
            )
        entries.append(
            f"// {fname} — {w}x{h} TRUE_COLOR_ALPHA, {len(payload)} bytes\n"
            f"static const uint8_t {stem}_data[] = {{\n"
            f"{hex_dump(payload)}\n"
            f"}};\n\n"
            f"const lv_img_dsc_t {stem}_dsc = {{\n"
            f"    .header = {{\n"
            f"        .cf = LV_IMG_CF_TRUE_COLOR_ALPHA,\n"
            f"        .always_zero = 0,\n"
            f"        .reserved = 0,\n"
            f"        .w = {w},\n"
            f"        .h = {h},\n"
            f"    }},\n"
            f"    .data_size = sizeof({stem}_data),\n"
            f"    .data = {stem}_data,\n"
            f"}};\n"
        )
        name_map.append(f'    {{"{stem}", &{stem}_dsc}},')

    out = []
    out.append("// icon_assets_baked.cpp — Generated by scripts/bake_icons_to_c.py.")
    out.append("// DO NOT EDIT BY HAND. Regenerate via:")
    out.append("//   python3 canshift-firmware/scripts/bake_icons_to_c.py")
    out.append("//")
    out.append("// In-flash LVGL image descriptors for icons that must never miss the")
    out.append("// cache (button icons, theme glyphs). Resolves issue #1261 — the")
    out.append("// SPIFFS path + heap gate combo could leave button icons blank after")
    out.append("// a tap + page-swipe roundtrip.")
    out.append("")
    out.append('#include "icon_assets_baked.h"')
    out.append("")
    out.append("#include <lvgl.h>")
    out.append("#include <stdint.h>")
    out.append("#include <string.h>")
    out.append("")
    out.append("namespace IconAssetsBaked {")
    out.append("")
    out.append("".join(entries))
    out.append("namespace {")
    out.append("struct Entry {")
    out.append("    const char *name;")
    out.append("    const lv_img_dsc_t *dsc;")
    out.append("};")
    out.append("")
    out.append("constexpr Entry kBakedIcons[] = {")
    out.extend(name_map)
    out.append("};")
    out.append("} // namespace")
    out.append("")
    out.append("const lv_img_dsc_t *resolve(const char *iconName) {")
    out.append("    if (!iconName || iconName[0] == '\\0')")
    out.append("        return nullptr;")
    out.append("    for (const auto &e : kBakedIcons) {")
    out.append("        if (strcmp(e.name, iconName) == 0)")
    out.append("            return e.dsc;")
    out.append("    }")
    out.append("    return nullptr;")
    out.append("}")
    out.append("")
    out.append("} // namespace IconAssetsBaked")
    out.append("")

    OUT_FILE.write_text("\n".join(out))

    # Run the project clang-format over the generated output so the CI
    # `clang-format --dry-run -Werror` gate stays clean without anyone having
    # to remember to re-format after regen. clang-format is a build-time
    # tool on every contributor machine via brew/apt; only warn if missing.
    if shutil.which("clang-format") is not None:
        subprocess.run(["clang-format", "-i", str(OUT_FILE)], check=True)
    else:
        print("warning: clang-format not found on PATH — generated file left unformatted")

    total = sum((ASSETS_DIR / f).stat().st_size for _, f in BAKED_ICONS)
    print(f"wrote {OUT_FILE} ({len(BAKED_ICONS)} icons, {total} bytes of pixel payload)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
