#!/usr/bin/env python3
"""Bake the brand monogram into src/ui/monogram_baked.cpp as LVGL images.

Rasterizes the brand monogram strokes (canshift-monogram.svg: stroke 13,
skewX(-11 deg), joins filled) at 4x supersampling, then emits RGB565+A8
(LV_IMG_CF_TRUE_COLOR_ALPHA, LV_COLOR_16_SWAP=0) C arrays at the sizes the
boot screens use. Run from canshift-firmware/:  python3 scripts/gen_monogram_c.py
"""

from __future__ import annotations

import struct
import sys
from pathlib import Path

SKEW_TAN = 0.19438  # tan(11 deg)
SS = 4  # supersample factor per axis

INK = (0xFF, 0xFF, 0xFF)
ACCENT = (0xFF, 0x47, 0x47)

STROKE_W = 13.0

C_PATH = [(46, 26), (22, 26), (22, 74), (46, 74)]

S_PATH = [(96, 26), (66, 26), (66, 50), (96, 50), (96, 74), (66, 74)]

SIZES = [("mark", 84), ("header", 32)]

ROOT = Path(__file__).resolve().parent.parent
OUT_CPP = ROOT / "src" / "ui" / "monogram_baked.cpp"
OUT_H = ROOT / "src" / "ui" / "monogram_baked.h"


def stroke_boxes(path: list[tuple[float, float]]) -> list[tuple[float, float, float, float]]:
    half = STROKE_W / 2.0
    boxes = []
    for (x0, y0), (x1, y1) in zip(path, path[1:]):
        if y0 == y1:
            boxes.append((min(x0, x1), y0 - half, max(x0, x1), y0 + half))
        else:
            boxes.append((x0 - half, min(y0, y1), x0 + half, max(y0, y1)))
    for x, y in path[1:-1]:
        boxes.append((x - half, y - half, x + half, y + half))
    return boxes


def unskew(px: float, py: float, scale: float) -> tuple[float, float]:
    y = py / scale
    return px / scale - 10.0 + SKEW_TAN * y, y


def in_boxes(px: float, py: float, boxes, scale: float) -> bool:
    x, y = unskew(px, py, scale)
    return any(x0 <= x <= x1 and y0 <= y <= y1 for x0, y0, x1, y1 in boxes)


def rasterize(height: int) -> tuple[int, int, bytes]:
    scale = height / 100.0
    shapes = [(stroke_boxes(C_PATH), INK), (stroke_boxes(S_PATH), ACCENT)]
    width = int(116.0 * scale + 0.5) + 1
    h = height + 1
    data = bytearray()
    for y in range(h):
        for x in range(width):
            cov = [0, 0]
            for sy in range(SS):
                py = y + (sy + 0.5) / SS
                for sx in range(SS):
                    px = x + (sx + 0.5) / SS
                    for i, (boxes, _) in enumerate(shapes):
                        if in_boxes(px, py, boxes, scale):
                            cov[i] += 1
                            break
            total = cov[0] + cov[1]
            if total == 0:
                data += b"\x00\x00\x00"
                continue
            color = INK if cov[0] >= cov[1] else ACCENT
            r, g, b = color
            rgb565 = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
            alpha = round(total * 255 / (SS * SS))
            data += struct.pack("<HB", rgb565, alpha)
    return width, h, bytes(data)


def hex_dump(data: bytes, indent: str = "    ") -> str:
    lines = []
    for i in range(0, len(data), 16):
        row = ", ".join(f"0x{b:02X}" for b in data[i : i + 16])
        lines.append(f"{indent}{row},")
    return "\n".join(lines)


def write_ppm(name: str, w: int, h: int, data: bytes) -> None:
    out = bytearray(f"P6\n{w} {h}\n255\n".encode())
    bg = (0x12, 0x12, 0x12)
    for i in range(0, len(data), 3):
        rgb565 = data[i] | (data[i + 1] << 8)
        a = data[i + 2]
        r = ((rgb565 >> 11) & 0x1F) << 3
        g = ((rgb565 >> 5) & 0x3F) << 2
        b = (rgb565 & 0x1F) << 3
        out += bytes(
            (bg[j] * (255 - a) + c * a) // 255 for j, c in enumerate((r, g, b))
        )
    Path(f"/tmp/monogram_{name}.ppm").write_bytes(out)


def main() -> int:
    blocks = []
    decls = []
    for name, height in SIZES:
        w, h, data = rasterize(height)
        write_ppm(name, w, h, data)
        blocks.append(
            f"static const uint8_t {name}_data[] = {{\n{hex_dump(data)}\n}};\n\n"
            f"static const lv_img_dsc_t {name}_dsc = {{\n"
            f"    .header = {{.cf = LV_IMG_CF_TRUE_COLOR_ALPHA, .always_zero = 0, .reserved = 0, .w = {w}, .h = {h}}},\n"
            f"    .data_size = sizeof({name}_data),\n"
            f"    .data = {name}_data,\n"
            f"}};\n"
        )
        decls.append(name)
        print(f"{name}: {w}x{h}, {len(data)} bytes")

    body = "".join(blocks)
    accessors = "\n\n".join(
        f"const lv_img_dsc_t *{name}() {{\n    return &{name}_dsc;\n}}" for name in decls
    )
    OUT_CPP.write_text(
        "// Generated by scripts/gen_monogram_c.py — do not edit.\n"
        '#include "monogram_baked.h"\n\n'
        "#include <lvgl.h>\n\n"
        "namespace MonogramBaked {\n\n" + body + "\n" + accessors + "\n\n} // namespace MonogramBaked\n"
    )
    OUT_H.write_text(
        "// Generated by scripts/gen_monogram_c.py — do not edit.\n"
        "#pragma once\n\n"
        "#include <lvgl.h>\n\n"
        "namespace MonogramBaked {\n"
        "const lv_img_dsc_t *mark();\n"
        "const lv_img_dsc_t *header();\n"
        "} // namespace MonogramBaked\n"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
