#!/usr/bin/env python3
"""Bake the brand monogram into src/ui/monogram_baked.cpp as LVGL images.

Rasterizes the exact stroke outlines of the bracket monogram (path stroke 13,
butt caps, skewX(-11 deg)) at 4x supersampling, then emits RGB565+A8
(LV_IMG_CF_TRUE_COLOR_ALPHA, LV_COLOR_16_SWAP=0) C arrays at the sizes the
boot screens use. Run from canshift-firmware/:  python3 scripts/gen_monogram_c.py
"""

from __future__ import annotations

import struct
import sys
from pathlib import Path

SKEW_TAN = 0.19438  # tan(11 deg)
SS = 4  # supersample factor per axis

INK = (0xFF, 0xFF, 0xFF)
ACCENT = (0xFF, 0x47, 0x47)

C_OUTLINE = [
    (46, 19.5), (15.5, 19.5), (15.5, 80.5), (46, 80.5),
    (46, 67.5), (28.5, 67.5), (28.5, 32.5), (46, 32.5),
]

S_OUTLINE = [
    (96, 19.5), (59.5, 19.5), (59.5, 56.5), (89.5, 56.5),
    (89.5, 80.5), (66, 80.5), (66, 67.5), (102.5, 67.5),
    (102.5, 43.5), (72.5, 43.5), (72.5, 32.5), (96, 32.5),
]

SIZES = [("mark", 84), ("header", 32)]

ROOT = Path(__file__).resolve().parent.parent
OUT_CPP = ROOT / "src" / "ui" / "monogram_baked.cpp"
OUT_H = ROOT / "src" / "ui" / "monogram_baked.h"


def skew(pts: list[tuple[float, float]], scale: float) -> list[tuple[float, float]]:
    return [((10.0 + x - SKEW_TAN * y) * scale, y * scale) for x, y in pts]


def point_in_polygon(px: float, py: float, poly: list[tuple[float, float]]) -> bool:
    inside = False
    n = len(poly)
    for i in range(n):
        x0, y0 = poly[i]
        x1, y1 = poly[(i + 1) % n]
        if (y0 > py) != (y1 > py):
            xint = x0 + (py - y0) * (x1 - x0) / (y1 - y0)
            if px < xint:
                inside = not inside
    return inside


def rasterize(height: int) -> tuple[int, int, bytes]:
    scale = height / 100.0
    polys = [(skew(C_OUTLINE, scale), INK), (skew(S_OUTLINE, scale), ACCENT)]
    width = int(116.0 * scale + 0.5) + 1
    h = height + 1
    data = bytearray()
    for y in range(h):
        for x in range(width):
            cov = [0, 0]
            for sy in range(SS):
                py = y + (sy + 0.5) / SS
                for sx in range(SS):
                    px = x + (sx + 0.5) / SS
                    for i, (poly, _) in enumerate(polys):
                        if point_in_polygon(px, py, poly):
                            cov[i] += 1
                            break
            total = cov[0] + cov[1]
            if total == 0:
                data += b"\x00\x00\x00"
                continue
            color = INK if cov[0] >= cov[1] else ACCENT
            r, g, b = color
            rgb565 = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
            alpha = round(total * 255 / (SS * SS))
            data += struct.pack("<HB", rgb565, alpha)
    return width, h, bytes(data)


def hex_dump(data: bytes, indent: str = "    ") -> str:
    lines = []
    for i in range(0, len(data), 16):
        row = ", ".join(f"0x{b:02X}" for b in data[i : i + 16])
        lines.append(f"{indent}{row},")
    return "\n".join(lines)


def write_ppm(name: str, w: int, h: int, data: bytes) -> None:
    out = bytearray(f"P6\n{w} {h}\n255\n".encode())
    bg = (0x12, 0x12, 0x12)
    for i in range(0, len(data), 3):
        rgb565 = data[i] | (data[i + 1] << 8)
        a = data[i + 2]
        r = ((rgb565 >> 11) & 0x1F) << 3
        g = ((rgb565 >> 5) & 0x3F) << 2
        b = (rgb565 & 0x1F) << 3
        out += bytes(
            (bg[j] * (255 - a) + c * a) // 255 for j, c in enumerate((r, g, b))
        )
    Path(f"/tmp/monogram_{name}.ppm").write_bytes(out)


def main() -> int:
    blocks = []
    decls = []
    for name, height in SIZES:
        w, h, data = rasterize(height)
        write_ppm(name, w, h, data)
        blocks.append(
            f"static const uint8_t {name}_data[] = {{\n{hex_dump(data)}\n}};\n\n"
            f"static const lv_img_dsc_t {name}_dsc = {{\n"
            f"    .header = {{.cf = LV_IMG_CF_TRUE_COLOR_ALPHA, .always_zero = 0, .reserved = 0, .w = {w}, .h = {h}}},\n"
            f"    .data_size = sizeof({name}_data),\n"
            f"    .data = {name}_data,\n"
            f"}};\n"
        )
        decls.append(name)
        print(f"{name}: {w}x{h}, {len(data)} bytes")

    body = "".join(blocks)
    accessors = "\n\n".join(
        f"const lv_img_dsc_t *{name}() {{\n    return &{name}_dsc;\n}}" for name in decls
    )
    OUT_CPP.write_text(
        "// Generated by scripts/gen_monogram_c.py — do not edit.\n"
        '#include "monogram_baked.h"\n\n'
        "#include <lvgl.h>\n\n"
        "namespace MonogramBaked {\n\n" + body + "\n" + accessors + "\n\n} // namespace MonogramBaked\n"
    )
    OUT_H.write_text(
        "// Generated by scripts/gen_monogram_c.py — do not edit.\n"
        "#pragma once\n\n"
        "#include <lvgl.h>\n\n"
        "namespace MonogramBaked {\n"
        "const lv_img_dsc_t *mark();\n"
        "const lv_img_dsc_t *header();\n"
        "} // namespace MonogramBaked\n"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
