#pragma once

#include <stddef.h>
#include <stdint.h>

#ifndef APP_VERSION_STR
    #define APP_VERSION_STR "0.0.0-unset"
#endif

#ifndef APP_DEBUG_BUILD
    #define APP_DEBUG_BUILD 0
#endif

#ifndef APP_SECURE_BOOT_BUILD
    #define APP_SECURE_BOOT_BUILD 0
#endif

#ifndef TASK_STACK_UI
    #define TASK_STACK_UI 8192
#endif
#ifndef TASK_STACK_CAN
    #define TASK_STACK_CAN 4096
#endif
#ifndef TASK_STACK_USB
    #define TASK_STACK_USB 4096
#endif
#define TASK_PRIO_UI 10
#define TASK_PRIO_CAN 15
#define TASK_PRIO_USB 8
#define TASK_PRIO_INPUT 7

#define TASK_CORE_UI 1
#define TASK_CORE_CAN 0
#define TASK_CORE_USB 1

#define TASK_CORE_INPUT 0

#ifndef TASK_STACK_INPUT
    #define TASK_STACK_INPUT 2048
#endif

#define TASK_WDT_TIMEOUT_MS 8000U

#define PRE_RESTART_FLUSH_DELAY_MS 200U

#ifndef APP_USB_TICK_TRACE
    #define APP_USB_TICK_TRACE 0
#endif

#define USB_TICK_DURATION_WARN_US 1000000UL

#define USB_TICK_INTERVAL_WARN_US 200000UL

#ifndef APP_USB_CAN_SCAN_FAIL_LOUD
    #define APP_USB_CAN_SCAN_FAIL_LOUD 0
#endif

#define LVGL_TICK_MS 5

#define LVGL_HANDLER_PERIOD_MS 10

#define SWIPE_CANCEL_THRESHOLD_PX 8

#define BUTTON_SIGNAL_SYNC_GRACE_MS 500

#ifndef APP_TOUCH_LATENCY_WARN_US
    #define APP_TOUCH_LATENCY_WARN_US 80000U
#endif

#define SETTINGS_OPEN_TAP_GUARD_MS 300

#ifdef __cplusplus
static constexpr size_t LVGL_FS_MIN_HEAP_BYTES = 256;
#else
    #define LVGL_FS_MIN_HEAP_BYTES 256
#endif

#define SIGNAL_STORE_MAX_SIGNALS 32

#define SIGNAL_DEFAULT_TIMEOUT_MS 1000

#define SIGNAL_EMA_ALPHA 0.2f

#ifdef __cplusplus
static constexpr uint8_t kCanFrameMaxBytes = 8;
#else
    #define CAN_FRAME_MAX_BYTES 8U
#endif

#define CAN_RX_QUEUE_DEPTH 32

#define CAN_TASK_YIELD_TICKS 1

#define TWAI_INIT_RETRY_MS 5000U
#define TWAI_INIT_MAX_RETRIES 6U

#define OBD2_REQUEST_FRAME_ID 0x7DFU
#define OBD2_RESPONSE_FRAME_ID 0x7E8U

#define OBD2_MIN_INTERVAL_MS_FW 100U
#define OBD2_MAX_INTERVAL_MS_FW 60000U

#define OBD2_MAX_POLL_SLOTS CONFIG_MAX_SIGNALS

#define CONFIG_JSON_DOC_DASHBOARD 16384
#define CONFIG_JSON_DOC_SIGNALS 4096

#define CONFIG_MAX_PAGES 8
#define CONFIG_MAX_WIDGETS_PER_PAGE 12
#define CONFIG_DASHBOARD_HEAP_BUDGET_BYTES (32u * 1024u)
#define CONFIG_MAX_SIGNALS 32

#define CFG_MAX_RAMP_STOPS 8

#ifndef DEFAULT_CONFIG_PROVISION_ENABLED
    #define DEFAULT_CONFIG_PROVISION_ENABLED 1
#endif

#define ERROR_STORE_RING_SIZE 6U

#define ALERT_REVLIMIT_WARN_PCT 95
#define ALERT_REVLIMIT_FLASH_PCT 100
#define ALERT_REVLIMIT_FLASH_HZ 8

#define ALERT_SENSOR_LOST_CLEAR_HOLD_MS 3000U

#define BATTERY_DEFAULT_LOW_WARN_V 12.0f
#define BATTERY_DEFAULT_LOW_CRIT_V 11.5f
#define BATTERY_DEFAULT_HIGH_WARN_V 15.0f
#define BATTERY_DEFAULT_HIGH_CRIT_V 16.0f

#ifndef APP_BLE_ENABLED
    #define APP_BLE_ENABLED 1
#endif

#ifndef BLE_DEFAULT_ENABLED
    #define BLE_DEFAULT_ENABLED 1
#endif

#ifndef TASK_STACK_BLE
    #define TASK_STACK_BLE 5120
#endif
#define TASK_PRIO_BLE 6
#define TASK_CORE_BLE 1

#define BLE_TELE_INTERVAL_MS 100

#define BLE_MIN_HEAP_BYTES (50U * 1024U)
#define BLE_GATT_MIN_HEAP_BYTES (24U * 1024U)

#define USB_RX_BUF_SIZE (CONFIG_JSON_DOC_DASHBOARD + 256)

#define USB_PROTOCOL_VERSION 2

#define BURN_OVERLAY_ERROR_HOLD_MS 3000

#ifndef APP_LOG_LEVEL
    #if APP_DEBUG_BUILD
        #define APP_LOG_LEVEL 4
    #else
        #define APP_LOG_LEVEL 1
    #endif
#endif

#define LOG_TAG_MAX_LEN 16

#ifndef APP_LV_TASK_LOG
    #define APP_LV_TASK_LOG 0
#endif

#ifndef APP_VERBOSE_DEBUG_LOGS
    #if APP_DEBUG_BUILD
        #define APP_VERBOSE_DEBUG_LOGS 1
    #else
        #define APP_VERBOSE_DEBUG_LOGS 0
    #endif
#endif
